'use client';

import Header from '../components/Header';
import Footer from '../components/Footer';
import SectionBadge from '../components/SectionBadge';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-brand-cream font-sans text-brand-navy selection:bg-brand-blue selection:text-white">
            <Header />

            {/* Hero */}
            <section className="pt-20 pb-12 text-center max-w-4xl mx-auto px-4">
                <SectionBadge>Legal</SectionBadge>
                <h1 className="text-5xl md:text-6xl font-bold mb-6 mt-4">
                    Terms and Conditions of Use
                </h1>
            </section>

            {/* Terms Content */}
            <section className="pb-20">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="prose prose-lg max-w-none text-gray-600">
                        <p className="text-lg font-semibold text-brand-navy mb-8">
                            PLEASE READ THESE TERMS AND CONDITIONS OF USE (THESE "TERMS") CAREFULLY. BY SETTING UP A USER ACCOUNT WITH US, OR BY ACCESSING, BROWSING, OR OTHERWISE USING OUR WEBSITE, CONTENT, OR SERVICES (ALL DEFINED BELOW), YOU ACCEPT AND AGREE TO BE BOUND TO COMPLY WITH THESE TERMS AND OUR PRIVACY POLICY (LINKED BELOW). IF YOU DO NOT AGREE TO BE BOUND, YOU ARE PROHIBITED FROM ANY AND ALL USE OF OUR WEBSITE, CONTENT, AND SERVICES THAT WOULD HAVE OTHERWISE BEEN PERMITTED UNDER THESE TERMS AND THE PRIVACY POLICY.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">1. Acceptance of the Terms</h2>
                        <p>
                            These Terms form a legally binding agreement between you and BuyUnrepped, Inc. ("BuyUnrepped", "we" or "us") governing the use of our website at BuyUnrepped.com (or as updated by BuyUnrepped from time to time) or social media or mobile applications (the "Website"), of "Content," which refers to any content generated by BuyUnrepped or by others for BuyUnrepped products or services, such as "User Submissions" (defined below), and of "Services," which are the services created, planned, implemented, or operated by BuyUnrepped, such as apps, plugins, executables, or other software or hardware or other products provided, installed, created, or operated by or on behalf of BuyUnrepped (the "Service(s)").
                        </p>
                        <p>
                            You represent and warrant that: (i) you are at least 18 years of age; or (ii) as parent or guardian, you agree to these Terms and the Privacy Policy (linked below) and you are responsible for the use of the Website, Content, or Services by any minor who is in your household or under your care or supervision.
                        </p>
                        <p>
                            If you are using or opening an account on behalf of a company, entity or organization, then you represent and warrant that you: (i) are an authorized representative of that entity with the authority to bind such entity to these Terms of Use and (ii) agree to be bound by these Terms of Use on behalf of such entity.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">2. Modifications to these Terms</h2>
                        <p>
                            These Terms may be changed, modified, amended, supplemented, or otherwise updated from time to time by BuyUnrepped without advance notice to you. By continuing to access, browse, or otherwise use the Website, Content, or Services, you are bound by any such updated Terms. BuyUnrepped, in its sole discretion, has the option, but not the obligation, to provide notice of any update to these Terms by means of a conspicuous alert, banner, or notification displayed on the Website or within the Services or by sending an email to the email address provided to BuyUnrepped.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">3. License Grant and Limitations</h2>
                        <p>
                            Subject to your compliance with these Terms, BuyUnrepped hereby grants you a non-transferable, nonsublicensable, non-assignable, revocable license in BuyUnrepped's rights in the Website, Content, and Services, to access and use them for your own personal and non-commercial use.
                        </p>
                        <p>
                            Except to the extent you are expressly granted other or additional rights in another written agreement signed by BuyUnrepped, the license granted herein excludes, and BuyUnrepped prohibits you from using BuyUnrepped's rights for, downloading (other than through page caching), copying, reproducing, extracting content or data from (including through data mining, web crawling, or other techniques), or modifying the Website, Content, or Services, or selling, reselling, or commercially reusing (including via any time-sharing, service bureau, or similar method), or creating any derivative works of the Website, Content, or Services. You are prohibited from, and BuyUnrepped does not grant you any rights to frame or use framing techniques on the Website, Content, or Services to enclose any trademark, logo, or other proprietary information that identifies BuyUnrepped or any third party, without the prior written consent of BuyUnrepped or, if applicable, the third-party owner of the trademark, logo, or other proprietary information.
                        </p>
                        <p>
                            BuyUnrepped reserves all rights and remedies available under contract or Applicable Law. BuyUnrepped does not grant you and BuyUnrepped disclaims all implied rights, to the extent permitted under Applicable Laws. "Applicable Laws" means any local, state, national, and international laws and regulations that apply, according to their provisions, to your activities with or use of the Website, Content, or Services.
                        </p>

                        <h3 className="text-xl font-bold text-brand-navy mt-8 mb-4">A. General</h3>
                        <p>
                            In connection with your use of the Website, Content, or Services, you agree and acknowledge that BuyUnrepped prohibits you from doing or from enabling or advising any other person or entity to engage in:
                        </p>
                        <ol className="list-[lower-alpha] pl-6 space-y-3">
                            <li>Uploading any message, information, data, text, software, or images, including, without limitation, any User Submission (as defined below), that is false, misleading, untruthful, inaccurate, unlawful, harmful, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, libelous, or otherwise objectionable, or that may invade another's right of privacy or publicity;</li>
                            <li>Creating a false identity for the purpose of misleading others or impersonating any person or entity, including, without limitation, any BuyUnrepped representative, or falsely stating or otherwise misrepresenting your affiliation with a person or entity;</li>
                            <li>Uploading or transmitting any User Submission, or other material or information, that you are prohibited from or limited in reproducing, displaying, or transmitting under any law, or under any contractual or fiduciary relationship (such as information that has been confidentially disclosed to you);</li>
                            <li>Uploading or transmitting any files or materials, including, without limitation, any User Submission, that contain viruses, trojan horses, worms, time bombs, cancel-bots, corrupted files, or any other similar software or programs that may damage the operation of the Website, Content, Services, another's computer system, data, or property of another;</li>
                            <li>Deleting any author attributions, legal notices, or proprietary designations or labels that you upload to any communication feature;</li>
                            <li>Violating any Applicable Laws;</li>
                            <li>Uploading or transmitting any User Submission or other material that infringes or misappropriates the intellectual property rights of BuyUnrepped or another person or entity;</li>
                            <li>Uploading or transmitting any User Submission or other material that constitutes unauthorized or unsolicited advertising, junk, Maillist, Listserve, or any form of auto-responder or bulk e-mail ("spamming"), or that involves commercial activities and/or sales without Company's prior written consent such as contests, sweepstakes, barter, advertising, or pyramid schemes;</li>
                            <li>Deleting or revising any information or material posted by another;</li>
                            <li>Manipulating or displaying the Website or Content, by using framing, mirroring, or similar navigational technology, or directly linking any site or social media platform to any subdomain of the Website or social media platform or site where the Content is posted online or published;</li>
                            <li>Probing, scanning, or testing the vulnerability of or breaching any authentication measures of the Website, Content, or Services, or in any related networks or systems;</li>
                            <li>Registering, subscribing, or unsubscribing, or attempting to do any of the foregoing, any persons or entities who are otherwise licensed by BuyUnrepped to use the Website, Content, or Services, without BuyUnrepped receiving from you in advance a written authorization for you to do so from such persons or entities;</li>
                            <li>Harvesting or otherwise collecting information about others, including e-mail addresses or other information that is "Personally Identifiable Information" or "PII" or the equivalent under Applicable Law, or that otherwise identifies a person or entity or their location, and as further prohibited or limited with respect to User Submission;</li>
                            <li>Using any robot, spider, scraper, or other automated or manual means to access, browse or otherwise use this Website or Services, or copy any of them;</li>
                            <li>Reverse engineering, decompiling, or otherwise attempting to derive the source code, techniques, processes, algorithms, know-how or other information from executable code portions of software in the Website or Services (collectively, "Reverse Engineering"), when enforcement of this limitation is not prohibited by Applicable Law. If Applicable Law prohibits enforcement of the Reverse Engineering prohibition, you may engage in Reverse Engineering solely to obtain information necessary to achieve interoperability with any software that is otherwise licensed to you by BuyUnrepped, or as otherwise permitted by Applicable Law, but only if: (a) Reverse Engineering is strictly necessary to obtain such information: and (b) you first requested such information from BuyUnrepped, and BuyUnrepped failed to make such information available under reasonable terms;</li>
                            <li>Taking any action that imposes or may impose (as determined by BuyUnrepped in its sole discretion) an unreasonable or disproportionately large load on BuyUnrepped's (or its third party providers') infrastructure;</li>
                            <li>Interfering or attempting to interfere with the proper working of the Service or any activities conducted on the Service;</li>
                            <li>Using any of BuyUnrepped's proprietary rights in the Website, Services, or Content to create, develop, or implement any new technology or services.</li>
                        </ol>

                        <h3 className="text-xl font-bold text-brand-navy mt-8 mb-4">B. User Submissions</h3>
                        <p>
                            Subject to the BuyUnrepped Privacy Policy, any communication or material that you transmit to the Website or to us, whether by email or other means, for any reason, will be treated as non-confidential and non-proprietary user generated content ("User Submission"). While you retain all ownership rights to the User Submission, you hereby grant to BuyUnrepped an irrevocable, perpetual, fully paid up, world-wide, royalty-free, right to use, reproduce, edit, alter, display, transmit, prepare derivate works of, modify, publish, and otherwise fully exploit any User Submission for any purpose related to the Services, including, without limitation, for the development, diagnosis, and improvement of the Website, the Services, or any other products and/or services hereinafter developed by BuyUnrepped without compensation to you. By posting any User Submission, you represent and warrant that you own or otherwise fully control all rights to your User Submission, including, without limitation, all the rights necessary for you to provide, post, upload, input, or otherwise submit your User Submission.
                        </p>
                        <p>
                            BuyUnrepped has no obligation to monitor the Website, Service, Content, or User Submissions. However, BuyUnrepped reserves the right to (i) remove, edit or modify any Content in its sole discretion, including without limitation any User Submissions, from the Website or Service at any time, without notice to you and for any reason (including, but not limited to, upon receipt of claims or allegations from third parties or authorities relating to such Content or if BuyUnrepped is concerned that you may have violated these Terms of Use), or for no reason at all and (ii) to remove or block any User Submissions from the Service.
                        </p>

                        <h3 className="text-xl font-bold text-brand-navy mt-8 mb-4">C. Other Content Related Prohibitions and Limitations</h3>
                        <p>
                            In connection with your use of the Content, and without limiting any of the above prohibitions or limitations, you agree and acknowledge that BuyUnrepped further prohibits you from doing or from enabling or advising any other person or entity to engage in:
                        </p>
                        <ul className="list-disc pl-6 space-y-3">
                            <li>Downloading, reproducing, preparing derivative works, distributing, or displaying any Content, except as set forth herein;</li>
                            <li>Using Content in connection with defamatory, or fraudulent content or in connection with pornographic, unlawful, or illegal images content, or any depictions of illegal activity whatsoever, whether directly or in context or by juxtaposition with other materials;</li>
                            <li>Removing any proprietary or intellectual property markings or notices on any Content; and</li>
                            <li>Violating, by bypassing or disregarding, other prohibitions, limitations, or restrictions in a subscription plan or other agreement with BuyUnrepped or authorized third-party content provider.</li>
                        </ul>

                        <h3 className="text-xl font-bold text-brand-navy mt-8 mb-4">D. Violation and Disclosure of Information</h3>
                        <p>
                            BuyUnrepped reserves the right to take whatever lawful actions it may deem appropriate in response to actual or suspected violations of the foregoing, including, without limitation, the suspension or termination of your access or your account. BuyUnrepped may cooperate with legal authorities or third parties in the investigation of any suspected or alleged crime or civil wrong. Except as may be expressly limited by our privacy policy, currently located at BuyUnrepped.com and incorporated into these Terms by this reference (our "Privacy Policy"), BuyUnrepped reserves the right at all times to disclose any information as BuyUnrepped deems necessary to satisfy Applicable Laws, or to edit, refuse to post or to remove any information or materials, in whole or in part, in BuyUnrepped's sole discretion.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">4. Access to Services and Your Account</h2>
                        <p>
                            To be allowed access and use of Services and any Content, you consent to being required to provide, and you will provide certain personally identifiable information, the use of which is governed by our Privacy Policy. You represent and warrant that any information provided by you is accurate, current, and complete and will be kept accurate, current, and complete when using the Services. BuyUnrepped may suspend, revoke, or terminate your access to the Services for any reason or no reason at any time in BuyUnrepped's sole discretion without prior notice to you. You must treat as confidential any username, password, or any other piece of information chosen by you, or provided to you as part of our security procedures, and you are prohibited from disclosing it to any other person or entity.
                        </p>
                        <p>
                            You must exercise caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. You understand and agree that if you are provided an account, your account is personal to you, and you are prohibited from providing any other person or entity with access to the Services and Content or portions thereof using your username, password, or other security information. You will notify us immediately of any unauthorized access to or use of your username or password or any other breach of security that has occurred or that you likely suspect to have occurred. You are responsible for password misuse and any unauthorized access.
                        </p>
                        <p>
                            The security of your personal information is very important to BuyUnrepped. We use physical, electronic, and administrative measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration, and disclosure. The safety and security of your information also depends on you. You are responsible for complying with these Terms and obtaining your own access to the Services and use of the Content. Unfortunately, the transmission of information is not completely secure, whether via the Internet, radio or wireless or other communication methods and systems. Although we do our best to protect your personal information, we cannot guarantee the security of personal information transmitted by you when using the Website, the Services, or any Content. Any transmission of personal information is at your own risk.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">5. Your Relationships with Us and Third Parties & Service Limitations</h2>

                        <h3 className="text-xl font-bold text-brand-navy mt-8 mb-4">A. Our Relationship with You</h3>
                        <p>
                            Unless a separate written agreement expressly states otherwise, BuyUnrepped provides non-representational brokerage facilitation, consulting, and transaction-coordination support. We do not act as your buyer&apos;s agent, negotiate, submit offers, or communicate with the listing side on your behalf. We provide transaction coordination, reminders, and guidance; you remain responsible for decisions and for communications made on your own behalf with the listing side and other parties. Your purchased service scope is defined by the applicable service agreement.
                        </p>
                        <p>
                            BuyUnrepped provides licensed brokerage services under Tennessee law. While we do not act as your buyer&apos;s agent, we remain licensed real estate professionals and owe the duties Tennessee law requires for the services we provide, including honesty, good faith, reasonable skill and care, confidentiality where applicable, and required disclosures.
                        </p>
                        <p>
                            We are not attorneys and do not provide legal, tax, lending, engineering, inspection, title, boundary, code, or utility advice. Comparative market analyses and broker price opinions are for informational purposes only; they are not appraisals and do not guarantee value, offer acceptance, or an appraisal outcome. Consult appropriately qualified professionals for advice outside the purchased scope.
                        </p>
                        <p>
                            BuyUnrepped may provide forms, market-analysis information, timeline tools, reminders, document organization, and educational guidance within your purchased tier. You are responsible for reviewing your documents, deciding whether to proceed, meeting contractual deadlines, and obtaining advice from qualified professionals when needed.
                        </p>

                        <h3 className="text-xl font-bold text-brand-navy mt-8 mb-4">B. Your Relationship with Listing Agents and Other Third Parties</h3>
                        <p>
                            Even though the listing agent does not represent you, he or she owes you certain duties under Tennessee law, including the duty to diligently exercise reasonable skill and care, to provide services with honesty and good faith, to disclose accurate information about market conditions in certain circumstances, to timely account to you for earnest money, to refrain from self-dealing unless disclosed to you. However, keep in mind that, at the end of the day, the listing agent represents the seller, not you.
                        </p>

                        <h3 className="text-xl font-bold text-brand-navy mt-8 mb-4">C. Fair Housing and Equal Opportunity</h3>
                        <p>
                            BuyUnrepped is committed to the letter and spirit of the federal Fair Housing Act and all applicable federal, state, and local fair housing laws. We do not discriminate, and we will not knowingly assist anyone in discriminating, against any person because of race, color, religion, sex, disability, familial status, national origin, or any other characteristic protected by applicable law. All housing services offered through BuyUnrepped are available on an equal opportunity basis.
                        </p>
                        <p>
                            Any market, neighborhood, school, or other information referenced on our website or provided during a transaction is general, publicly available information offered for your independent review only. We do not steer buyers toward or away from any property or area on the basis of a protected characteristic, and we do not evaluate, rank, or recommend communities on that basis. We encourage every buyer to make an independent evaluation of any property and community, including verifying school assignments directly with the applicable school district and reviewing objective, publicly available data.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">6. Fees; Renewals and Cancellation</h2>
                        <p>
                            Fees may be subject to tax, collected by us or a third party through which you transact, and except as set out in these Terms are non-refundable. If your Service involves a recurring payment of a fee, unless you notify us before a charge that you want to cancel or do not want to automatically renew your Service, you understand it will automatically continue and you authorize us, or a third party through which you transact (without notice to you, unless required by applicable law) to collect the then-applicable fee and any taxes, using any credit card we have on record for you. You can cancel at any time by emailing us at BuyUnrepped.com. If you cancel your plan or Service, you will not receive a refund of any fees already paid, unless otherwise stated in these Terms.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">7. Termination; Modifications</h2>
                        <p>
                            The Services, Content, plan, and any features, information, or content available therein, may be changed, canceled, withdrawn, or terminated at any time in BuyUnrepped's sole discretion without notice to you. We shall not be liable to you or any third party for any claims for damages arising out of any termination or suspension or any other actions taken by us in connection therewith.
                        </p>
                        <p>
                            Additionally, we reserve the right to accept, refuse, or restrict your use of any plan or Service, or change your plan or Service based on your qualification for a specific plan or Service, in our sole discretion. You may not transfer or assign your plan or Service benefits, or any Content you access. We may take actions we deem reasonably necessary to prevent fraud and abuse, including placing restrictions on all or a subset of the users on your account or on the amount of Content that can be accessed at any one time.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">8. Links to Third-Party Sites</h2>
                        <p>
                            The Website, Content, and Services may contain links to certain third-party media platforms or other sites. These sites are not under the control of BuyUnrepped. In addition, third-party sites may contain links to our Website or Content. BuyUnrepped is not responsible for or liable for, and makes no representations or warranties concerning, the content or material or other information streamed or posted at such third-party sites. The fact that the Website or Content links to any third-party site, or that a third-party site has provided a link to this Website or Content, does not constitute an endorsement, authorization, sponsorship, or affiliation between BuyUnrepped and such third-party site's owners, operators, or maintainers. You acknowledge that any services, content, material, or information provided through such third-party sites are accessed at your own risk. BuyUnrepped is not responsible for, and BuyUnrepped is not liable for, and BuyUnrepped makes none and disclaims any and all representations and warranties, with respect to, any particular information, software, products, services, or content found on any linked third-party sites, including, without limitation, the appropriateness of any products, services, or transactions described therein.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">9. No Reliance</h2>
                        <p>
                            The content provided through the Website, Content, and Services is for general informational and educational purposes only. Although we make reasonable efforts to update information, we make no representations, warranties, or guarantees, whether express or implied, that it is accurate, complete, or current. Your use of the Website, Content, and Services is at your own risk.
                        </p>
                        <p>
                            The Website, Content, and Services may include content provided by third parties, including from other users and third-party licensors. All statements and/or opinions expressed in any such third-party content, other than the content provided by BuyUnrepped, are solely the opinions and the responsibility of the person or entity providing those materials. Such materials do not necessarily reflect the opinion of BuyUnrepped. Neither BuyUnrepped, nor its respective directors, officers, employees, agents, service providers, contractors, licensors, licensees, suppliers, or successors have any responsibility or liability whatsoever to you, or any third party, for the content or accuracy of any third-party materials.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">10. Ownership</h2>
                        <p>
                            The Website, Services, and Content, including, but not limited to, all information, software, code, data text, displays, graphics, photographs, images, video, audio, music, broadcast, design, presentation, website layout, selection, and arrangement are owned by BuyUnrepped, its licensors, or other providers of such material and are protected in all forms by intellectual property laws, including, without limitation, copyright, trademark, patent, trade secret, and any other proprietary rights.
                        </p>
                        <p>
                            All trademarks, service marks, logos, product and service names, designs, images, and slogans are trademarks appearing within the Website, Content, or Services are owned by BuyUnrepped or its affiliates or licensors. You are prohibited from using any such marks without the prior written permission of BuyUnrepped. Other names, logos, product and service names, designs, images, and slogans mentioned, or which appear within the Website, or on the Services or the Content, are the trademarks of their respective owners. Use of any such property, except as expressly authorized, shall constitute an infringement or violation of the rights of the property owner and may be a violation of federal or other laws and could subject the infringer to legal action. BuyUnrepped does not make any non-infringement representation or warranty, and disclaims all, with respect to your use of the Website, any Content, or the Services, or the materials or other information therein or related thereto.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">11. Confidentiality</h2>
                        <p>
                            During your relationship with BuyUnrepped, you may be exposed to, or BuyUnrepped may disclose to you information that is confidential or under a restricted use or restricted disclosure or otherwise under an ongoing confidentiality obligation (any of which is "Confidential Information"). BuyUnrepped is not under any obligation to share any Confidential Information with you. If Confidential Information is shared or accessed by you, unless you can demonstrate at the time of receipt or access, with contemporaneously dated written records that the information was generally and freely available to the public before your access or receipt thereof, you will maintain the confidentiality of the Confidential Information, you will not share it with anyone or publish or post it anywhere, without BuyUnrepped's prior written consent, and you can only use it on an as-needed basis solely in connection with your use of the Website, Services, or Content as licensed by BuyUnrepped in these Terms or as otherwise set forth in another written agreement that you may enter into with BuyUnrepped. With respect to meeting these confidentiality obligations, you will use at least the same degree of care that you use with your own confidential information to safeguard it against disclosure and misuse, but in no event less than reasonable care. If you are required to disclose any if required by a law or court or governmental agency, you may do so, only to the extent required, if you give BuyUnrepped reasonable notice and opportunity to contest, protect, or restrict the disclosure to extent reasonably practicable. If your relationship with BuyUnrepped is terminated under these Terms or other written agreement between you and BuyUnrepped, or at any earlier time upon BuyUnrepped's request, you will promptly return all Confidential Information to BuyUnrepped, or confirm that it has all been destroyed, including whatever materials or information you may have created that is based on or otherwise contains any Confidential Information. You do not have any claim, right, title, property or other interest or license of any kind or nature in Confidential Information. You will hold the Confidential Information in strict confidence and in trust for the sole and exclusive benefit of BuyUnrepped. BuyUnrepped makes no, and expressly disclaims, all representations and warranties, express and implied, as to the accuracy or completeness of Confidential Information or otherwise. You will not share with BuyUnrepped any information or materials that you hold confidential, or that you hold confidential for a third party, and BuyUnrepped is not obligated or liable to you in any way with respect to the information that you provide to BuyUnrepped.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">12. Developments</h2>
                        <p>
                            Company does not grant any rights (and Customer hereby disclaims any such grant) to use Company's Confidential Information or Company's intellectual property in any manner beyond what is expressly set forth in this Agreement. Customer is prohibited from carrying out any research and development activities that may lead to the disclosure by any of them to third parties of Company's intellectual property that comprises either Confidential Information or proprietary know-how, in each case proprietary to Company and not generally known to the public. Should any new or improved technology, material, or processes, which is developed by or on behalf of Customer, be related to methods and technology that are proprietary to Company, including its affiliates, in whole or in part, then Customer hereby grants to Company, at no cost, a non-exclusive, irrevocable, transferrable license to all such developments.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">13. Third Party Platforms</h2>
                        <p>
                            BuyUnrepped may provide tools that enable you to link your account with third-party applications, websites, and other services to the Services and Content available to you as a user. If you do so, you may also be subject to the terms and conditions and privacy policy of the provider of that third-party service provider. BuyUnrepped is not responsible or liable for behavior, content or features of any third-party application, website, or service.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">14. Disclaimers</h2>
                        <p className="uppercase font-semibold">
                            EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE WEBSITE, SERVICES, AND CONTENT ARE PROVIDED ON AN "AS IS," "WHERE IS," AND "AS AVAILABLE" BASIS. BUYUNREPPED MAKES NO, AND HEREBY DISCLAIMS ANY, REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, WITH RESPECT TO THE WEBSITE, SERVICES, AND CONTENT, AS WELL AS THE AVAILABILITY, FUNCTIONALITY, PERFORMANCE, LOSS OF DATA OR RESULTS OF USE OF THE WEBSITE, SERVICES, AND CONTENT. WITHOUT LIMITING THE FOREGOING, BUYUNREPPED EXPRESSLY DISCLAIMS ANY WARRANTY THAT THE WEBSITE, SERVICES, OR CONTENT WILL BE ACCURATE, ERROR-FREE, OR UNINTERRUPTED. FURTHER, TO THE FULL EXTENT PERMISSIBLE BY LAW, BUYUNREPPED DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR ARISING BY USAGE OF TRADE, NONINFRINGEMENT, COURSE OF DEALING OR COURSE OF PERFORMANCE. FURTHER, AND WITHOUT LIMITING THE FOREGOING, BUYUNREPPED MAKES NO REPRESENTATION OR WARRANTY, AND DISCLAIMS ANY REPRESENTATION OR WARRANTIES OF ANY KIND THAT WEBSITE, CONTENT OR SERVICES, INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING APPS) OR OTHER SERVICES INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH THE BUYUNREPPED WEBSITE, CONTENT OR SERVICES, BUYUNREPPED'S SERVERS OR ELECTRONIC COMMUNICATIONS SENT FROM BUYUNREPPED ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">15. Indemnification</h2>
                        <p>
                            To the maximum extent permitted by Applicable Law, you will defend, indemnify, and hold harmless BuyUnrepped, its subsidiaries, affiliates, and their respective directors, officers, employees, agents, service providers, contractors, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys' fees) arising out of or relating to your breach of these Terms or your use of the Services or any Content, including, but not limited to, actions under your account name, your violation of any Applicable Law or of any rights of another, your User Submission, third-party sites, and any use of content other than as expressly authorized under these Terms. We reserve the right, at your expense, to assume the exclusive defense and control of any matter which you are required to indemnify against, and you agree to cooperate in our defense of such matter. This indemnification will survive any termination of these Terms.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">16. Limitations</h2>
                        <p className="uppercase font-semibold">
                            NEITHER PARTY WILL BE HELD LIABLE TO THE OTHER PARTY OR CLAIM OR HOLD THE OTHER PARTY LIABLE FOR CONSEQUENTIAL, SPECIAL, INDIRECT, INCIDENTAL, PUNITIVE, OR EXEMPLARY DAMAGES, SUCH AS COSTS OR EXPENSES INCURRED IN CONNECTION WITH THE REPLACEMENT OF ANY PRODUCTS, GOODS, MATERIALS, OR SERVICES BOUGHT OR SOLD THROUGH THE WEBSITE OR THE SERVICES, OR ANY OTHER LOSSES, LOST PROFITS, LOSS OF DATA, OR OPPORTUNITY COSTS, WHETHER IN CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF THE OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, EXCEPT TO THE EXTENT THAT A PARTY IS LIABLE TO INDEMNIFY THE OTHER, OR LIABLE DUE TO THE PARTY'S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT.
                        </p>
                        <p className="uppercase font-semibold">
                            NEITHER PARTY WILL BE LIABLE TO THE OTHER PARTY OR CLAIM OR HOLD THE OTHER PARTY LIABLE FOR ANY AMOUNTS IN EXCESS OF ONE HUNDRED DOLLARS ($100.00). THIS LIMITATION OF LIABILITY IS CUMULATIVE AND NOT PER INCIDENT (i.e., THE EXISTENCE OF MORE THAN ONE (1) CLAIM WILL NOT ENLARGE THIS LIMIT), EXCEPT TO THE EXTENT THAT A PARTY IS LIABLE TO INDEMNIFY THE OTHER, OR LIABLE DUE TO THE PARTY'S GROSS NEGLIGENCE OR WILLFUL MISCONDUCT. ANY CLAIM OR CAUSE OF ACTION BROUGHT BY YOU OR ON YOUR BEHALF, ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICES OR THE CONTENT OR OUR RELATIONSHIP WITH YOU, REGARDLESS OF THEORY, MUST BE BROUGHT WITHIN ONE (1) YEAR AFTER THE OCCURRENCE OF THE EVENT GIVING RISE TO THE CLAIM OR CAUSE OF ACTION OR BE FOREVER BARRED.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">17. International Use, Sanctions, and Export Policy</h2>
                        <p>
                            Although this Website may be accessible worldwide, BuyUnrepped makes no representation that materials on this Website are appropriate or available for use in locations outside the United States. Those who choose to access this Website from other locations do so on their own initiative and at their own risk. If you choose to access this Website from outside the United States, you are responsible for compliance with local laws in your jurisdiction, including but not limited to, the taxation of products purchased over the Internet. Any offer for any Content or Service, or materials or information made in connection with this Website, Content, or Services, is void where prohibited. You are prohibited from using any BuyUnrepped Website, Content, or Services, if you are the subject of U.S. sanctions or of sanctions consistent with U.S. law imposed by the governments of the country where you are using the Website, Content or Services. You are required and solely responsible to comply with all U.S. or other export and re-export restrictions that may apply to goods, software, technology, and services.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">18. Infringement Notices</h2>
                        <p>
                            If you believe that any content on the Website or the Services or any other Content violates or infringes upon your intellectual property rights pursuant to Title 17, United States Code, Section 512(c)(2), please notify us immediately of the alleged infringement at Michael Johnson, Kay Griffin Evans, PLLC, 222 Second Avenue North, Nashville, Tennessee 37201 with all specifics necessary for us to consider and respond to your complaint. You may be asked to provide additional information and follow additional procedures for us to act on your complaint.
                        </p>
                        <p>
                            If you learn that the Website, Content, or any Services are subject to a threatened or actual third-party claim of infringement, violation of another right, or any other claim for which BuyUnrepped, Content contributors, or any of their respective affiliates may be liable, you will promptly notify BuyUnrepped of any such claim. If BuyUnrepped, the Content contributors, or any of their respective affiliates learns of such a claim from you, the third party or otherwise and BuyUnrepped, in its sole good faith discretion, determine that the claim raises an inappropriate legal risk, upon notice from us, you will: (i) remove Content from your computer systems and storage devices (electronic or physical), and (ii) cease any future use of the Website, Services, and Content at your own expense if possible. If you do remove and cease use of Website, Services, or Content, we may choose to refund your fees for future use, or without charge provide you with other services or content that we determine with your consent, not to be unreasonably withheld or delayed, is comparable, subject to the other terms and conditions of these Terms. Repeat infringers will be terminated and barred from using the Website, Services, or Content.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">19. Binding Arbitration</h2>
                        <p>
                            Any dispute or claim relating in any way to these Terms, or your use of the Website, Content, or Service will be resolved by binding arbitration, rather than in court, except that you may assert claims in small claims court if your claims qualify. The Federal Arbitration Act and federal arbitration law apply to this agreement. There is no judge or jury in arbitration, and court review of an arbitration award is limited. However, an arbitrator can award on an individual basis the same damages and relief as a court (including injunctive and declaratory relief or statutory damages) and must follow these Terms, as a court would be bound to follow. To begin an arbitration proceeding you must send a letter requesting arbitration and describing your claim to the attention of Michael Johnson, at Kay Griffin Evans, PLLC, 222 Second Avenue North, Nashville, TN 37201. The arbitration will be conducted by the American Arbitration Association (AAA) under its rules, including the AAA's Supplementary Procedures for Consumer-Related Disputes. The AAA's rules are available at www.adr.org or by calling 1-800-778-7879. Payment of all filing, administration, and arbitrator fees will be governed by the AAA's rules. We will reimburse those fees for claims totaling less than $10,000 unless the arbitrator determines the claims are frivolous. Likewise, BuyUnrepped will not seek attorney fees and costs in arbitration unless the arbitrator determines the claims are frivolous. You may choose to have the arbitration conducted by telephone, based on written submissions, or in person in the Venue or at another mutually agreed location. We each agree that any dispute resolution proceedings will be conducted only on an individual basis and not in a class, consolidated or representative action. If for any reason a claim proceeds in court rather than in arbitration, we each waive any right to a jury trial. We also both agree that you or we may bring a legal proceeding before a court to enjoin infringement or other misuse of intellectual property rights.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">20. Jurisdiction and Governing Law</h2>
                        <p>
                            These Terms shall be construed, governed, and enforced under the laws of the United States and the State of Tennessee (without regard to rules governing conflict of laws). You consent to the venue being in Nashville, Tennessee for all actions relating in any manner to these Terms. If the Arbitration clause is found to be unenforceable, each party hereby consents and submits to the in personam jurisdiction of the federal or state courts located in Nashville, Tennessee, and to the extent permitted by law, hereby consents that all services of process may be made by any nationally recognized overnight courier, or by certified or registered mail, postage prepaid and return receipt requested. Each party waives any objection based on forum non conveniens and waives any objection to venue of any action instituted hereunder to the extent that an action is brought in the courts identified above. Each party agrees that a final judgment in any such action shall be conclusive and may be enforced in any other jurisdiction in any manner provided by law.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">21. Electronic Communications</h2>
                        <p>
                            When you use the Website or Services, or send electronic communications to us, you consent to receive service-related communications electronically, including notices and messages related to your inquiry or purchased services. Marketing email is sent only when you affirmatively opt in, and you may unsubscribe at any time. We do not obtain consent for marketing calls or texts through these Terms. You agree that electronic agreements, notices, disclosures, and other service-related communications may satisfy legal requirements for a writing where permitted by law.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">22. Force Majeure</h2>
                        <p>
                            In addition to any excuse provided by applicable law, BuyUnrepped shall be excused from liability for non-delivery or delay in delivery of products, Content, or Services available through our Website arising from any event beyond our reasonable control, whether or not foreseeable by either party, including but not limited to: labor disturbance, war, fire, accident, adverse weather, disease, pandemic, inability to secure transportation, governmental act or regulation, and other causes or events beyond our reasonable control, whether or not similar to those which are enumerated above.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">23. Severability</h2>
                        <p>
                            If any part of these Terms is held illegal, or otherwise invalid or incapable of being enforced in a jurisdiction, that portion shall be excluded, replaced, or construed in a manner consistent with Applicable Law in that jurisdiction to reflect, as nearly as possible, the original intentions of the parties, and the remaining portions shall remain in full force and effect. The foregoing rights to exclude, replace, or re-construe do not automatically apply to the legality, validity, and enforceability of the terms in other jurisdictions, which shall, to the extent permitted by Applicable Law, remain unaltered as originally set forth herein.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">24. Entire Agreement</h2>
                        <p>
                            These Terms constitute the entire agreement and understanding between the parties concerning the subject matter hereof and supersede all prior agreements and understandings of the parties with respect thereto. These Terms may NOT be altered, supplemented, or amended by any other document(s) other than a written agreement entered into with signatures of authorized representatives of both parties.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">25. Compliance with Laws</h2>
                        <p>
                            You agree to abide by all Applicable Laws. You are solely responsible and liable for all acts or omissions that occur as a result of or while you access, browse, or otherwise use the Website, Content, or Services.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">26. Order of Precedence</h2>
                        <p>
                            To the extent that anything in or associated with this Website, Services, or Content is in conflict or inconsistent with these Terms, these Terms shall take precedence. To the extent that anything in or associated with these Terms is in conflict or inconsistent with another written agreement that you may enter into with BuyUnrepped, including a master service agreement or other written contract, that other written agreement shall take precedence.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">27. Survival</h2>
                        <p>
                            The Terms shall survive termination or expiration of your use of the Website, the Services, Content, or your plan.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">28. Third-Party Beneficiary</h2>
                        <p>
                            BuyUnrepped, its content contributors, or any of their respective affiliates are all intended third-party beneficiaries of these Terms; nothing in these Terms, express or implied, intends to or confers upon any other third party any rights, benefits, or remedies of any nature whatsoever. You will promptly reimburse BuyUnrepped, its content contributors, and any of their respective affiliates for any costs (including reasonable attorneys' fees and court costs) incurred in collecting any fees or enforcing these Terms.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">29. Waiver</h2>
                        <p>
                            No failure to exercise, or delay in exercising, any right, remedy, power, or privilege arising from these Terms operates, or may be construed, as a waiver thereof; and no single or partial exercise of any right, remedy, power, or privilege hereunder precludes any other or further exercise thereof or the exercise of any other right, remedy, power, or privilege.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">30. Our Remedies</h2>
                        <p>
                            You acknowledge and agree that any violation, or threatened violation, by you of these Terms constitutes an unlawful and unfair business practice that will cause us irreparable and unquantifiable harm, and as such, you consent to our seeking injunctive or equitable relief that we deem necessary or appropriate in response. These remedies are in addition to any other remedies we may have at law or in equity.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">31. Notice</h2>
                        <p>
                            You may notify BuyUnrepped at info@BuyUnrepped.com or by certified mail to the address below.
                        </p>
                        <p className="mt-4">
                            By Mail, with attention to Management:
                        </p>
                        <address className="not-italic mt-2">
                            BuyUnrepped<br />
                            2509 Cruzen St<br />
                            Nashville, TN 37211
                        </address>
                        <p className="mt-4">
                            Please ensure that all notifications from you include your name, address, e-mail address, and account number and project identification if applicable.
                        </p>
                        <p>
                            BuyUnrepped may notify you by email or certified mail associated with you, your computer's IP address, and if you have an account or project with BuyUnrepped, then the information associated with the account or project.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">32. Independent Contractors</h2>
                        <p>
                            You and BuyUnrepped agree and acknowledge that nothing in these Terms will be construed as creating a joint venture, partnership, franchise, agency, employer/employee, or similar relationship between you and BuyUnrepped, or as authorizing either to act as agent or representative of the other. You are and will remain an independent contractor in your relationship with BuyUnrepped, and you have no right or authority to bind BuyUnrepped to a third party, or to make any representations or warranties or statements on behalf of BuyUnrepped to a third party.
                        </p>
                    </div>
                </div>
            </section>

            <Footer />
        </div>
    );
}
