'use client';

import Header from '../components/Header';
import Footer from '../components/Footer';
import SectionBadge from '../components/SectionBadge';

export default function PrivacyPage() {
    return (
        <div className="min-h-screen bg-brand-cream font-sans text-brand-navy selection:bg-brand-blue selection:text-white">
            <Header />

            {/* Hero */}
            <section className="pt-20 pb-8 text-center max-w-4xl mx-auto px-4">
                <SectionBadge>Legal</SectionBadge>
                <h1 className="text-5xl md:text-6xl font-bold mb-6 mt-4">
                    Privacy Policy
                </h1>
                <p className="text-lg text-gray-500">
                    Updated: September 1, 2024
                </p>
            </section>

            {/* Privacy Policy Content */}
            <section className="py-8 md:py-16">
                <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
                    <div className="prose prose-lg max-w-none text-gray-600">
                        <p className="mb-6">
                            At BuyUnrepped, Inc. (individually and collectively referred to as "Company," "us" or "we") we value your privacy. This privacy policy ("Policy") applies to the use of all our web properties, including this site (collectively the "Site"), describing our privacy practices for the Site, as well as audio, video, imagery or other content that is generated by us or others on our behalf, concerning us or our products or services (any and all of which is "Content"), and to the ordering, requesting, use, or purchase of any of the products or services that we offer or make available to you, or that we facilitate in offering or making available to you (any and all of which are the "Products and Services"). This Policy also applies to how your personal and other information received from you is collected, treated, and used by us. Please read the information.
                        </p>

                        <p className="mb-6">
                            You agree and acknowledge that this Privacy Policy is designed to be read in connection with the Site Terms of Use, and that by accessing or using our Site, you agree to be bound by the Site's terms and conditions, as well as this Privacy Policy.
                        </p>

                        <p className="mb-6">
                            We reserve the right to change this Privacy Policy from time to time. We will notify you about significant changes in the way we treat personal information by sending a notice to the primary email address specified in your account, by placing a prominent notice on our site, and by updating any privacy information on this page. Your continued use of the Site and or any Content, Products, or Services made available through this Site after such modifications will constitute your: (a) acknowledgment of the modified Policy; and (b) your agreement to abide and be bound by that Policy.
                        </p>

                        <p className="mb-6">
                            At the same time, we will not discriminate against you for exercising your rights as mandated or required under applicable local laws and regulations, and our intent is that those mandates and requirements are incorporated herein by reference and control in the event of a conflict between them and this Privacy Policy.
                        </p>

                        <p className="mb-6">
                            For example, you may exercise certain rights to review information collected about you, deleting any or all of it, correcting it, and opting out of cookie or other information collection, learn about and opt out of financial incentives offered with certain information collection, which are available to residents of California when browsing or using a device with an IP address that places the device within California (see Californian privacy rights under the CCPA), or similar options and rights legislated in Colorado (see{' '}
                            <a href="https://coag.gov/resources/colorado-privacy-act/" className="text-brand-blue hover:underline" target="_blank" rel="noopener noreferrer">https://coag.gov/resources/colorado-privacy-act/</a> and{' '}
                            <a href="https://coag.gov/app/uploads/2023/03/FINAL-CLEAN-2023.03.15-Official-CPA-Rules.pdf" className="text-brand-blue hover:underline" target="_blank" rel="noopener noreferrer">https://coag.gov/app/uploads/2023/03/FINAL-CLEAN-2023.03.15-Official-CPA-Rules.pdf</a>), and in Virginia ({' '}
                            <a href="https://www.oag.state.va.us/consumer-protection/files/tips-and-info/Virginia-Consumer-Data-Protection-Act-Summary-2-2-23.pdf" className="text-brand-blue hover:underline" target="_blank" rel="noopener noreferrer">https://www.oag.state.va.us/consumer-protection/files/tips-and-info/Virginia-Consumer-Data-Protection-Act-Summary-2-2-23.pdf</a> and{' '}
                            <a href="https://law.lis.virginia.gov/vacode/title59.1/chapter53/" className="text-brand-blue hover:underline" target="_blank" rel="noopener noreferrer">https://law.lis.virginia.gov/vacode/title59.1/chapter53/</a>).
                        </p>

                        <p className="mb-6">
                            ALL QUESTIONS, QUERIES, APPEALS, AND THE LIKE, about the Privacy Policy or the information collected about you, or compliance with applicable laws and regulations, should be submitted to our main query email address, with subject header "PRIVACY POLICY" and sufficient detail, including your contact information so that we can work with you to address the particular question, issue or concern: Our main query email address is:{' '}
                            <a href="mailto:info@buyunrepped.com" className="text-brand-blue hover:underline">info@buyunrepped.com</a>.
                        </p>

                        <div className="bg-white p-6 rounded-xl my-8 border border-gray-100">
                            <p className="font-bold text-brand-navy mb-4">
                                IMPORTANT: BY USING THE SITE, OR CONTENT, PRODUCTS, OR SERVICES AVAILABLE OR OFFERED THROUGH THE SITE:
                            </p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>YOU GIVE YOUR CONSENT THAT ALL PERSONAL DATA YOU SUBMIT MAY BE PROCESSED BY US IN THE MANNER AND FOR THE PURPOSES DESCRIBED BELOW. IF YOU DO NOT AGREE TO THESE TERMS AND CONDITIONS, DO NOT USE THE SITE, CONTENT, OR SERVICES.</li>
                                <li>YOU REPRESENT AND WARRANT THAT: (i) YOU ARE AT LEAST 18 YEARS OF AGE; OR (ii) YOU ARE USING THIS UNDER THE CARE AND SUPERVISION OF A PARENT AND GUARDIAN WHO AGREES TO THE PRIVACY POLICY, AND WHO IS SOLELY RESPONSIBLE FOR YOUR USE OF THE SITE, CONTENT, OR PRODUCTS OR SERVICES.</li>
                            </ul>
                        </div>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">1. Types of Information We Collect</h2>
                        <p className="mb-6">
                            We collect two types of information about our users: Personally Identifiable Information ("PII") and Aggregated Information.
                        </p>
                        <p className="mb-6">
                            "Personally Identifiable Information" or "PII" is information that lets us know the specifics of who you are. When you engage in certain activities on this Site, such as registering for an account, downloading, or purchasing a product or service, submitting content, or posting content, or sending us feedback, we may ask you for certain information about yourself. Examples of PII may include your first and last name, email address, billing address (including ZIP code), IP address, and other identifying information.
                        </p>
                        <p className="mb-6">
                            Aggregated Information is information that does not by itself identify a specific individual. We gather certain information about you based upon where you visit on our Site and what other sites may have directed you to us. This information, which is collected in a variety of different ways, is compiled, and analyzed on both a personal and an aggregated basis. This information may include the Website's Uniform Resource Locator ("URL") that points to the site you just came from, which URL you go to after visiting our Site, what browser you are using, and your Internet Protocol ("IP") address.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">2. How We Collect and Use Information</h2>
                        <p className="mb-6">
                            We do not collect any of your PII unless you voluntarily provide it to us. However, you may be required to provide certain PII to us when you elect to order or use certain Content, Products, or Services that you order or access through the Site. Examples of when you may be required to provide certain PII are: (a) registering for an account with us; (b) entering a contest or sweepstakes sponsored by us or a Provider (defined below); (c) signing up for special offers from selected third parties; (d) sending us an email message; or (e) submitting a form or transmitting other information by telephone or letter. When processing certain information, we encrypt the transaction, using Secure Socket Layer (SSL) encryption technology, to make it more secure against being stolen, intercepted, or misused.
                        </p>
                        <p className="mb-6">
                            We will primarily use your PII to make Product and Service offerings available to you. We will also use certain forms of PII to enhance the operation of our Site, improve our internal marketing and promotional efforts, statistically analyze Site use, improve our product and service offerings, and customize our Site's content, layout, and services. We may use PII to deliver information to you and to contact you regarding administrative notices. Finally, we may use your PII to resolve disputes, troubleshoot problems and enforce our agreements with you, including our Terms of Use, and this Privacy Policy.
                        </p>
                        <p className="mb-6">
                            We may also collect and use certain Aggregated Information. For example, we may use your IP address to diagnose problems with our servers, software, to administer our Site and to gather demographic information.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">3. Cookies</h2>
                        <p className="mb-6">
                            Depending on how you use our Site, we may store cookies on your computer to collect certain Aggregated Information about our users and to customize certain aspects of your specific user experience. A cookie is a small data text file that is stored on your computer that uniquely identifies your browser. Cookies may also include more personalized information, such as your IP address, browser type, the server your computer is logged onto, the area code and ZIP code associated with your server, and your first name to welcome you back to our Site. We may use cookies to perform tasks such as: monitoring aggregate site usage metrics, storing, and remembering your passwords (if you allow us to do so), storing account and advertising preferences that you have set, and personalizing the offerings that we make available to you. However, we do not store cookies to track your browsing behaviors. Most browsers are initially set up to accept cookies, but you can reset your browser to refuse all cookies or to indicate when a cookie is being sent.
                        </p>
                        <p className="mb-6">
                            As a courtesy, we provide links below with instructions on how to alter cookies, and other information collection and sharing with various browsers, and other third-party internet service providers. This list is not exhaustive, and you are solely responsible for finding and using the most updated link addresses.
                        </p>

                        <div className="overflow-x-auto mb-6">
                            <table className="min-w-full border border-gray-200 rounded-lg">
                                <thead className="bg-white">
                                    <tr>
                                        <th className="px-4 py-3 text-left text-sm font-semibold text-brand-navy border-b">Provider/App/Service</th>
                                        <th className="px-4 py-3 text-left text-sm font-semibold text-brand-navy border-b">Current URL</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr className="border-b">
                                        <td className="px-4 py-3 text-sm">Chrome; Firefox; Internet Explorer / Edge; Opera; Safari</td>
                                        <td className="px-4 py-3 text-sm">
                                            <a href="https://support.microsoft.com/en-us/topic/description-of-cookies-ad01aa7e-66c9-8ab2-7898-6652c100999d" className="text-brand-blue hover:underline break-all" target="_blank" rel="noopener noreferrer">https://support.microsoft.com/en-us/topic/description-of-cookies-ad01aa7e-66c9-8ab2-7898-6652c100999d</a>
                                        </td>
                                    </tr>
                                    <tr className="border-b">
                                        <td className="px-4 py-3 text-sm">Flash cookies</td>
                                        <td className="px-4 py-3 text-sm">
                                            <a href="https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html" className="text-brand-blue hover:underline break-all" target="_blank" rel="noopener noreferrer">https://www.macromedia.com/support/documentation/en/flashplayer/help/settings_manager07.html</a>
                                        </td>
                                    </tr>
                                    <tr className="border-b">
                                        <td className="px-4 py-3 text-sm">Opt out of Google Tracking Analytics</td>
                                        <td className="px-4 py-3 text-sm">
                                            <a href="https://tools.google.com/dlpage/gaoptout" className="text-brand-blue hover:underline break-all" target="_blank" rel="noopener noreferrer">https://tools.google.com/dlpage/gaoptout</a>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td className="px-4 py-3 text-sm">Digital Advertising Alliance tools</td>
                                        <td className="px-4 py-3 text-sm">
                                            <a href="https://optout.aboutads.info/" className="text-brand-blue hover:underline break-all" target="_blank" rel="noopener noreferrer">https://optout.aboutads.info/</a> and{' '}
                                            <a href="https://optout.privacyrights.info" className="text-brand-blue hover:underline break-all" target="_blank" rel="noopener noreferrer">https://optout.privacyrights.info</a>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>

                        <p className="mb-6">
                            If you modify or block cookies and tracking tools or other information collection and tracking, certain features with respect to our Site, it may impair functionality of links and programming through Content, but it will not stop all the tracking described in this Policy.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">4. Release of Information</h2>
                        <p className="mb-6">
                            We will not sell, trade, or rent your PII to others. We do offer some Products and Services through contractual arrangements made with advertisers, and other service or product providers, some of which are affiliates and others of which are third parties that we work with from time to time ("Providers"). We and our Providers may need to use some of your PII to perform tasks between our respective sites, or to deliver products or services to you. We encourage our Providers to adopt and promote strong privacy policies. However, the use of your PII by our Providers is governed by their own respective privacy policies and is under their control, not ours. Except as otherwise discussed in this Privacy Policy, this document only addresses the use and disclosure of information we collect from you. Other sites accessible through our Site, including our advertisers, and our other Providers, have their own privacy policies and data collection, use, and disclosure practices. Please consult each Site's privacy policy. We are not responsible for the policies or practices of our Providers or other third parties.
                        </p>
                        <p className="mb-6">
                            Occasionally, we may be required by law enforcement or judicial authorities to provide PII to the appropriate governmental authorities. In such cases, we will disclose PII upon receipt of a court order, subpoena, or for cooperating with a law enforcement investigation. We fully cooperate with law enforcement agencies in identifying those who use our Site, Content, or product or service offerings for illegal activities. We reserve the right to report to law enforcement agencies any activities that we in good faith believe to be unlawful.
                        </p>
                        <p className="mb-6">
                            We may also provide Aggregated Information about our customers' sales, traffic patterns, and related Site information to third-party advertisers, but these statistics do not include any PII.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">5. Updating and Correcting Information</h2>
                        <p className="mb-6">
                            We believe you should have the ability to access and edit the PII that you have provided to us. You may change any of your PII in your account online at any time by linking to your account in accordance with instructions posted elsewhere on this Site. You may also access and correct your personal information and privacy preferences by emailing us at{' '}
                            <a href="mailto:info@buyunrepped.com" className="text-brand-blue hover:underline">info@buyunrepped.com</a>, or writing to us at:
                        </p>

                        <div className="bg-white p-6 rounded-xl mb-6 border border-gray-100">
                            <p className="font-semibold">Attn: Privacy Compliance</p>
                            <p>BuyUnrepped.com</p>
                            <p>2509 Cruzen St</p>
                            <p>Nashville, TN 37211</p>
                        </div>

                        <p className="mb-6">
                            Please include your name, mailing address, and email address when you contact us.
                        </p>
                        <p className="mb-6">
                            We encourage you to promptly update your PII if it changes. Also, depending on your location, you may have certain additional rights with respect to your information such as deletion (including the right to have the Company delete your personal information, except information we are required to retain, by contacting us at the address listed above), or we may delete your data if we are instructed to do so by our customers who export your personal information to us, except for information we are required to retain; and withdrawal of consent or object to processing (including, in limited circumstances, the right to ask the Company to stop processing your personal data, by contacting us at the address listed above).
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">6. User Choices on Collection and Use of Information</h2>
                        <p className="mb-6">
                            If you indicated upon registration or otherwise that you are interested in receiving offers or information from us and our Providers, then we may from time to time, send you emails, call you, or send you direct mail about Products and Services that may be of interest to you. We (or agents working on our behalf under confidentiality agreements) are the only ones who will send you these solicitations, and only if you have previously indicated that you wish to receive them. If you change your mind after giving consent to receive these solicitations, you can "opt-out" by 1) selecting the "unsubscribe" link at the end of our communications to you; 2) responding to any of our text messages with any of the following replies: STOP, END, CANCEL, UNSUBSCRIBE, or QUIT; 3) logging into the Site or Services and adjusting your user preferences in your account profile; or 4) sending us an email at{' '}
                            <a href="mailto:info@buyunrepped.com" className="text-brand-blue hover:underline">info@buyunrepped.com</a> stating your request.
                        </p>
                        <p className="mb-6">
                            You also have choices with respect to cookies, as described above. By modifying your browser preferences, you have the choice to accept all cookies, to be notified when a cookie is set, or to reject all cookies. If you choose to reject all cookies some parts of our Site may not work properly in your case.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">7. Security of Your PII</h2>
                        <p className="mb-6">
                            At our Site, you can be assured that your PII is secure, consistent with current industry standards. We strive to take appropriate security measures to protect against unauthorized access to or unauthorized alteration, disclosure, or destruction of your PII.
                        </p>
                        <p className="mb-6">
                            We work hard to ensure that the data we collect is reliable, accurate, complete, and current. We encrypt all PII, to protect against unauthorized parties viewing such information when it is transmitted to us. The collected information, even if kept indefinitely, is used only for the purposes for which it was collected or to comply with any applicable legal or ethical reporting or document retention requirements.
                        </p>
                        <p className="mb-6">
                            We limit access to PII only to specific employees, contractors, and agents who have a reasonable need for that access. For example, we may provide members of our technical support team with limited access to your account to allow them to troubleshoot problems that you may be having with the Site.
                        </p>
                        <p className="mb-6">
                            We also employ numerous physical, electronic, and procedural safeguards to protect your rights in your PII. Our secure servers and our data centers are protected by industry-standard encryption, and our servers reside behind firewalls and employ high-level password protection.
                        </p>
                        <p className="mb-6">
                            Finally, you always have your own secure access to your PII that we have collected and kept in our system, through a password and unique customer ID selected by you. This password is encrypted. We recommend that you safeguard and do not share your password with anyone so that you do not compromise its security, integrity, and privacy.
                        </p>
                        <p className="mb-6">
                            Unfortunately, there is no way to give a 100% guarantee of security for any data transmission over the Internet or through any other communication channel. As a result, while we strive to protect your PII, you acknowledge that: (a) there are features inherent to the Internet and other communication networks which limit our ability to preserve data security, integrity, and privacy in ways that are beyond our control; and (b) the security, integrity, and privacy of information and other data that you exchange with us through this Site or through other communication channels cannot be guaranteed.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">8. Questions, Comments, or Complaints</h2>
                        <p className="mb-6">
                            If you have questions or comments about this Privacy Policy, or if you are not completely satisfied with this Privacy Policy or its application by us, we invite you to convey your concerns or suggestions to us at{' '}
                            <a href="mailto:info@buyunrepped.com" className="text-brand-blue hover:underline">info@buyunrepped.com</a>. If you have an applicable disability, you may also contact us at the above email address to request access to this Privacy Policy an alternative format. We will reply as quickly as possible and inform you of the steps, if any, that have been or will be taken in order to address your concern or implement the suggestion.
                        </p>

                        <h2 className="text-2xl font-bold text-brand-navy mt-12 mb-4">9. Miscellaneous</h2>
                        <p className="mb-6">
                            You must be at least 13 years old to have our permission to use this Site, or Content, or order any Products or Services. If you are not at least 13 years old, your use and activities are supervised by your parent or guardian, who represents that they are solely responsible for your use and activities with respect to the Site, Content, and any Products and Services.
                        </p>
                        <p className="mb-6">
                            Our policy is that we do not knowingly collect, use, or disclose PII about children.
                        </p>
                        <p className="mb-6">
                            You should also be aware that when PII is voluntarily disclosed (e.g., your name, email address, etc.) in the discussion forums or other public areas on this Site, that information, along with any information disclosed in your communication, can be collected, and used by third parties and may result in unsolicited messages (including unwanted spam messages) from third parties. Such activities are beyond our control and this Policy does not apply to such information. Please consult our Terms of Use for our Site conduct policies.
                        </p>
                        <p className="mb-6">
                            If you have any questions, concerns, or inquiries about our Privacy Policy, our use of your PII, or our privacy practices, please contact us at{' '}
                            <a href="mailto:info@buyunrepped.com" className="text-brand-blue hover:underline">info@buyunrepped.com</a>. You can also reach our Privacy Compliance department by sending written correspondence to:
                        </p>

                        <div className="bg-white p-6 rounded-xl mb-6 border border-gray-100">
                            <p className="font-semibold">Attn: Privacy Compliance</p>
                            <p>BuyUnrepped</p>
                            <p>2509 Cruzen St</p>
                            <p>Nashville, TN 37211</p>
                        </div>
                    </div>
                </div>
            </section>

            <Footer />
        </div>
    );
}
